spring.application.name=homey-finances
spring.datasource.url=jdbc:postgresql://localhost:5432/homey_finances
spring.datasource.username=postgres
spring.datasource.password=Wz3Vj6#A7NV$G^64B2s5


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true